fastq ファイルから centromere reads の QV score を抽出して保存する。

In [1]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
from IPython.display import display
import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.io as pio
pio.templates.default = 'plotly_white'
import logging
import logzero
logzero.loglevel(logging.INFO)

In [2]:
dir_fname = 'work'
import os
os.chdir(dir_fname)

In [3]:
from BITS.util.io import load_pickle, save_pickle

In [4]:
centromere_reads_fname = "centromere_reads_incl_low_cover_rate_all_sync.pkl"
centromere_reads = load_pickle(centromere_reads_fname)

In [5]:
import numpy as np
import pandas as pd
from BITS.clustering.seq import ClusteringSeq
from BITS.seq.align import EdlibRunner
from BITS.seq.consed import ConsedRunner
from BITS.util.io import save_pickle, load_pickle

In [6]:
from BITS.seq.io import load_fastq

In [7]:
fastq_reads = load_fastq("../../../data/dmel_pacbio_ccs/m64011_190605_003147.Q20.fastq.1", only_qual=True)

In [8]:
centromere_names = {read.name for read in centromere_reads}

In [9]:
centromere_phreds = {}
for read in centromere_reads:
    pre, mid, suf = read.name.split('/')
    centromere_phreds[read.name] = np.array(fastq_reads[f"{pre}/{mid}/ccs"], dtype=np.int16)

In [10]:
list(centromere_phreds.items())[:10]

[('m64011_190605_003147/1362/0_13814',
  array([76, 93, 93, ..., 93, 78, 74], dtype=int16)),
 ('m64011_190605_003147/2726/0_11859',
  array([49, 79, 44, ..., 50, 31, 37], dtype=int16)),
 ('m64011_190605_003147/67744/0_11396',
  array([93, 93, 93, ..., 93, 37, 10], dtype=int16)),
 ('m64011_190605_003147/132129/0_13059',
  array([93, 93, 93, ..., 82, 85, 92], dtype=int16)),
 ('m64011_190605_003147/197132/0_12117',
  array([93, 93, 93, ..., 93, 93, 93], dtype=int16)),
 ('m64011_190605_003147/197657/0_11453',
  array([23, 28, 22, ..., 55, 76, 53], dtype=int16)),
 ('m64011_190605_003147/263915/0_12867',
  array([93, 48, 93, ..., 93, 93, 93], dtype=int16)),
 ('m64011_190605_003147/264172/0_14494',
  array([93, 93, 93, ..., 93, 93, 93], dtype=int16)),
 ('m64011_190605_003147/394357/0_12351',
  array([ 9, 10, 20, ..., 52, 42, 61], dtype=int16)),
 ('m64011_190605_003147/394384/0_12604',
  array([93, 47, 93, ..., 93, 93, 45], dtype=int16))]

In [11]:
save_pickle(centromere_phreds, "centromere_phreds_incl_low_cover_rate_all_sync.pkl")